channels:
  - conda-forge
dependencies:
  - defaults::python=3.9.7
  - tqdm=4.62.3

  - pytorch::pytorch=1.7.1
  - pytorch::torchvision=0.8.2
  - pytorch::torchaudio=0.7.2
  - defaults::cudatoolkit=11.3
  - tensorboard=2.7.0

  - numpy=1.21.4
  - scikit-learn=1.0.1
  - pandas=1.3.4
  - openpyxl=3.0.9
  - tabulate=0.8.9
  - matplotlib=3.4.3
  - protobuf=3.15.8 # 适应 spikingjelly 依赖 onnx 1.8.0
  - loris=0.5.3

  - pip=21.3
  - pip:
    - -e spikingjelly
